[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux"]


# [shell.selection]
# save_to_clipboard = true
